services:
  find-my-kids:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: find-my-kids
    ports:
      - "7020:7020"
    env_file:
      - .env
    volumes:
      - ./find-my-kids/images:/app/images
      - ./find-my-kids/config:/app/config
      - ./find-my-kids/classifiers:/app/classifiers
    restart: unless-stopped 